export enum Icon {
  Error = 'error',
  VisibilityOff = 'visibility_off',
  Visibility = 'visibility',
  List = 'list',
  Add = 'add',
  Delete = 'delete',
  ArrowUpward = 'arrow_upward',
  ArrowDownward = 'arrow_downward',
  Edit = 'edit',
  PowerSettingsNew = 'power_settings_new',
  Search = 'search',
  ChecklistRtl = 'checklist_rtl',
  Copy = 'content_copy',
  Group = 'group',
}
