trigger:
- master

resources:
- repo: self

variables:
  githubUser: 'lukasz-porebski'
  repoName: 'quizi-web'
  imageName: 'ghcr.io/$(githubUser)/$(repoName)'
  buildTag: '$(Build.BuildId)'
  latestTag: 'latest'

stages:
- stage: Docker
  displayName: Build and Push Docker Image
  jobs:
  - job: Docker
    displayName: Docker Build & Push
    pool:
      vmImage: ubuntu-latest
    steps:
    # 1️⃣ Login do GHCR
    - task: Docker@2
      displayName: Login to GitHub Container Registry
      inputs:
        command: login
        containerRegistry: GitHubConnection

    # 2️⃣ Build Docker image
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        repository: $(imageName)
        tags: |
          $(buildTag)
          $(latestTag)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

    # 3️⃣ Show local images
    - script: docker images
      displayName: Show Docker images

    # 4️⃣ Push Docker image
    - task: Docker@2
      displayName: Push Docker image to GHCR
      inputs:
        command: push
        repository: $(imageName)
        tags: |
          $(buildTag)
          $(latestTag)
