steps:
  # Lint
  - name: 'node:22'
    entrypoint: 'sh'
    secretEnv: ['GITHUB_COMMON_PACKAGES_ACCESS_TOKEN']
    args:
      - '-c'
      - |
        echo "//npm.pkg.github.com/:_authToken=$$GITHUB_COMMON_PACKAGES_ACCESS_TOKEN" >> .npmrc
        echo "@lukasz-porebski:registry=https://npm.pkg.github.com" >> .npmrc
        npm ci && npx ng lint
        rm .npmrc

  # Budowa obrazu Docker
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['GITHUB_COMMON_PACKAGES_ACCESS_TOKEN']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg GITHUB_TOKEN=$$GITHUB_COMMON_PACKAGES_ACCESS_TOKEN \
          -t gcr.io/$PROJECT_ID/quizi-web:latest \
          .

  # Push do Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/quizi-web'
      ]

  # Deploy do Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'quizi-web',
        '--image', 'gcr.io/$PROJECT_ID/quizi-web',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--service-account', '${_SERVICE_ACCOUNT}',
        '--set-env-vars', 'API_URL=${_API_URL}'
      ]

images:
  - 'gcr.io/$PROJECT_ID/quizi-web'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-common-packages-access-token/versions/latest
      env: 'GITHUB_COMMON_PACKAGES_ACCESS_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_ACCOUNT: ''
  _API_URL: ''
  _REGION: ''
