steps:
  # 1️⃣ Build obrazu Dockera z Angulara
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quizi-web', '.']

  # 2️⃣ Push obrazu do Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quizi-web']

images:
  - 'gcr.io/$PROJECT_ID/quizi-web'

# Logi tylko w Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
